### ISSUE TITLE
Locale information is not uniform

### ISSUE THREAD

**Issue by Luis-Cruz** [ist-dsi/fenix-ist#13]
Some pages present the locale information as "PT | EN" while others present as "PT-PT | EN-GB".

In this latter case, mouse over gives no additional information.

On pages where the mouse over feature is more informative, the first letter of a language should be upper case.

Also, the presentation of the locales description should always be given it that locale, and not in the locale the user has currently, suggested. Note that a user that cannot understand Portuguese may not know that Inglês means English.

Finally, if possible, whenever there is only one option for a certain language, then the location information is useless and should be omitted.

**Comment by jcarvalho** [comment]
This decision is up to each individual theme. The 'ashes' theme is now uniform.
