### ISSUE TITLE
Repeated menu item on personal page

### ISSUE THREAD

**Issue by pedrorijo91** [ist-dsi/fenix-ist#20]
Multiple "Apresentação" items on sidebar menu in personal page: https://fenix.tecnico.ulisboa.pt/homepage/ist167060/
![captura de ecra 2014-09-10 as 10 14 17](https://cloud.githubusercontent.com/assets/1999050/4215172/8d8ada28-38cb-11e4-9830-be68c2b3280f.png)

**Comment by jcarvalho** [comment]
With the new FenixEdu CMS, this issue is no longer applicable.
