### ISSUE TITLE
Bug(?) na página de login do fenix / IST email

### ISSUE THREAD

**Issue by BrunoMSantos** [ist-dsi/fenix-ist#41]
Apercebi-me hoje de que não me é possível entrar no fenix ou no cliente online de email no Firefox em Linux (64bits). Este problema não deve ter (muito) mais do que um mês já que em Dezembro, pelo menos, lembro-me de logar no fenix.

Em Windows não tenho qualquer problema, e em Linux, o thunderbird continua a receber e a enviar emails com sucesso.
Julgo que o problema será exclusivo à página de login quando num ambiente Linux e possivelmente isolado ao Firefox.

Testado em Arch Linux.

**Comment by nurv** [comment]
Este issue não tem a ver com a instancia de FenixEdu do IST. Contacta o suporte da DSI (dsi@tecnico.ulisboa.pt)
